name: Github Actions Example

on:
  push:
    branches:
      main

jobs:
  run-a-python-script:
    runs-on: ubuntu-lastest
    steps: 
      - name: Checkout repo content
        uses: actions/checkout@v3
      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Run the python script
        run: python script.py